### ISSUE TITLE
Datapoint ID is unique to plant

### ISSUE THREAD

**Issue by uphillbattle** [sindrebroch/flexit#1]
Kudos! Great integration! Installed it manually in custom_components today and can confirm that it works - after a small tweak - on my internet connected Flexit Nordic S4.

In `const.py`, all the `_PATH`s include a datapoint ID. In your code, it starts with `P9eedfcc2-`. This ID is unique to each plant and can be found by `https://api.climatixic.com/Plants/?tenantId=XXXX`. It is the the value with key `id`. After I replaced your ID with my own, the integration works.

In `const.py` I modified the code as follows:

```
BINARY_SENSOR_LIST = list(BINARY_SENSOR_DICT)

PLANT_ID = "My-plant-id"

VENTILATION_MODE_PATH = PLANT_ID + ";1!013000169000055"
VENTILATION_MODE_PUT_PATH = PLANT_ID + ";1!01300002A000055"
OUTSIDE_AIR_TEMPERATURE_PATH = PLANT_ID + ";1!000000001000055"
...
```

The plant id (or datapoint id, whatever it should be called) should be found during integration config instead of hard-coded as in your (and my) code.

Otherwise - excellent work! :smile: :clap:

**Comment by sindrebroch** [comment]
Great suggestion, will push a fix when I get the chance. Thanks! 😄

**Comment by sindrebroch** [comment]
Should be fixed with the latest release, closing for now :)
